# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c32fa88b423044f414bf606d4cd737d3"
name = "ipblocker"
handle = "ipblocker"
application_url = "https://ipblocker.shopifyplugins.pro/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes

[auth]
redirect_urls = [ "https://ipblocker.shopifyplugins.pro/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
