# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c32fa88b423044f414bf606d4cd737d3"
name = "Value IP Blocker Bot Blocker"
handle = "ipblocker"
application_url = "https://ipblocker.valuecommerce.info/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://ipblocker.valuecommerce.info/auth/callback",
  "https://ipblocker.valuecommerce.info/auth/shopify/callback",
  "https://ipblocker.valuecommerce.info/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  uri = "https://ipblocker.valuecommerce.pro/compliances/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://ipblocker.valuecommerce.pro/compliances/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://ipblocker.valuecommerce.pro/compliances/shop_redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
