# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d316e3df7a533ea58135040b5750498b"
name = "Ipblocker"
handle = "ipblocker-3"
application_url = "https://alberta-louisiana-info-eco.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-da31056d.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://alberta-louisiana-info-eco.trycloudflare.com/auth/callback",
  "https://alberta-louisiana-info-eco.trycloudflare.com/auth/shopify/callback",
  "https://alberta-louisiana-info-eco.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
