# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c32fa88b423044f414bf606d4cd737d3"
name = "Value IP Blocker"
handle = "ipblocker"
application_url = "https://ipblocker.valuecommerce.info"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mvllp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes, unauthenticated_read_checkouts, read_shipping, read_customers,read_products,read_inventory"

[auth]
redirect_urls = [
  "https://telephone-giants-terms-descending.trycloudflare.com/auth/callback",
  "https://telephone-giants-terms-descending.trycloudflare.com/auth/shopify/callback",
  "https://telephone-giants-terms-descending.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://ipblocker.valuecommerce.pro/compliances/customers_redact"
  customer_data_request_url = "https://ipblocker.valuecommerce.pro/compliances/customers_data_request"
  shop_deletion_url = "https://ipblocker.valuecommerce.pro/compliances/shop_redact"
